### ISSUE TITLE
Warning	A non-numeric value encountered

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/undo#13]
<details>
<summary>System report (REDAXO 5.8.0-beta1, PHP 7.3.8)</summary>

| REDAXO        |             |
| ------------: | :---------- |
|       Version | 5.8.0-beta1 |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.8      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | 5.5.5-10.1.41-MariaDB-0ubuntu0.18.04.1 |
| Character set | utf8 (utf8_general_ci)         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Safari/12.1.2 |
|      Protocol | HTTP/1.0      |
|         HTTPS | yes           |

| Packages          |             |
| ----------------: | :---------- |
|            backup | 2.4.0-beta1 |
|          be_style | 2.8.0-beta1 |
|   be_style/redaxo | 2.8.0-beta1 |
|           install | 2.5.0       |
|            mblock | 3.1.0       |
|     media_manager | 2.7.0-beta1 |
|         mediapool | 2.6.0-beta1 |
|          metainfo | 2.5.0-beta1 |
|             mform | 5.3.1       |
|        mform/docs | 1.0         |
|              plyr | 3.1.0       |
|           project | dev         |
|         structure | 2.8.0-beta1 |
| structure/content | 2.8.0-beta1 |
|  uikit_collection | 1.4.0       |
|              undo | 2.1.2       |
|          uploader | 2.0.4       |
|             users | 2.5.2       |

</details>

```
20.08.2019 12:01:53	
Warning	A non-numeric value encountered	
redaxo/src/addons/undo/boot.php
156 
20.08.2019 12:01:53	
Warning	A non-numeric value encountered	
redaxo/src/addons/undo/boot.php
156
```

**Comment by hirbod** [comment]
Nur PHP 7.3 oder?

**Comment by skerbis** [comment]
auch auf anderem System mit 7.2.18

**Comment by hirbod** [comment]
Ok, danke. Mir fällt auf, das die Undo's letztes Update auf einem 7.0 System entwickelt habe, deswegen ist das untergegangen.

**Comment by hirbod** [comment]
@skerbis ich kann diesen Fehler nicht reproduzieren. Weder auf PHP 7.2 noch auf 7.3. Error Reportings sind ebenfalls aktiv. Im Redaxo Log stehen auch nur Warnings und Notices von yRewrite.

**Comment by hirbod** [comment]
Ich bin aber auch auf REDAXO 5.7.1 fällt mir auf - teste es mal damit.
EDIT: mit 5.8 ebenfalls nicht reproduzierbar. Irgendwelche besonderen Schritte die das auslösen?

**Comment by staabm** [comment]
man muss das addon so bedienen dass man in dieser zeile vorbeikommt:
https://github.com/FriendsOfREDAXO/undo/blob/0cbf3a6f9b08e3f25ab5b263def59e225a1c08d2/boot.php#L156

**Comment by hirbod** [comment]
Ja, aber ich würd gern wissen wie es im "normalen" UX Fluss provoziert wird. Vermutlich ist der undo_timestamp nen string.. Bzw initial ist es gar nicht gesetzt.

**Comment by hirbod** [comment]
Ok, konnte es reproduzieren. Der Fehler tritt auf, wenn man etwas löscht und sich gleich danach ausloggt und dann wieder einloggt.

**Comment by skerbis** [comment]
@Hirbod @staabm Ich weiß leider auch nicht wie der Fehler im Log entstanden ist. Ist mir halt in 2 Instanzen aufgefallen. Danke @Hirbod. Scheint aktuell nicht mehr aufzutauchen.
