### ISSUE TITLE
Achtung .. die revision müssen noch beachtet werden

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/undo#2]
d.h. auch der artikel select müsste einen subselect haben, da es mehrere Versionen geben kann.

**Comment by hirbod** [comment]
Aktuell stellt das nur den _letzten_ Stand wieder her. Muss da sicher etwas beachtet werden? Ich konnte zusammen mit dem History-Addon keine Fehler feststellen

**Comment by dergel** [comment]
z.b. arbeitsversion bekommt, soweit ich weiss, revision = 1.. diese ist dann auch gelöscht und wird nicht wieder hergestellt. Was auch nicht superdramatisch wäre. Aber wäre halt besser

**Comment by hirbod** [comment]
@dergel ok, habs verstanden. Ich werde das demnächst mit aufnehmen.

**Comment by skerbis** [comment]
So wie ich das aktuell sehe wird die Arbeitsversion wieder hergestellt.
