### ISSUE TITLE
Fehler mit Kategorie-Prio

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/undo#5]
Irgendwas stimmt mit der Kategorie-Prio noch nicht ganz. Könnte hier Hilfe gebrauchen, damit beim Wiederherstellen auch wirklich wieder die richtige Prio gesetzt wird.

**Comment by hirbod** [comment]
https://github.com/FriendsOfREDAXO/undo/blob/master/boot.php#L69
https://github.com/FriendsOfREDAXO/undo/blob/master/boot.php#L77

irgendwas mache ich hier falsch

**Comment by staabm** [comment]
warum ist newprio immer 0?

**Comment by hirbod** [comment]
Weil ich das irgendwie nicht richtig verstanden habe

**Comment by staabm** [comment]
an welcher position soll ein artikel nach "rückgängig" stehen?

**Comment by hirbod** [comment]
An der selben, wo es vorher war
