### ISSUE TITLE
Fehler beim Löschen eines Artikels

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/undo#8]
![bildschirmfoto 2017-03-17 um 12 35 19](https://cloud.githubusercontent.com/assets/791247/24041545/38127ec6-0b0e-11e7-8101-cdca037304ab.png)

**Comment by hirbod** [comment]
Das hat höchstwahrscheinlich mit nem Core-Update zu tun, siehe README. Sobald irgend ein AddOn (z.B. bloecks) oder der Core die Datenbankspalten verändert, muss undo deinstalliert und anschließend installiert werden (nicht re-installieren, da hatte nicht funktioniert in meinen Tests)

Dann sollte es im Anschluss wieder funktionieren.

**Comment by skerbis** [comment]
ah! Danke @Hirbod , funktioniert

**Comment by hirbod** [comment]
Ich suche trotzdem nach einer Idee, wie ich das abfangen kann.

**Comment by hirbod** [comment]
Fixed https://github.com/FriendsOfREDAXO/undo/commit/478b8fd43d411698d2166b0dc3ab6ec5fd666137

Passiert nicht mehr

**Comment by skerbis** [comment]
🤝
